#spring.application.name=telegramBot
server:
  port: 8081
spring:
  application:
    name: telegramBot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otus
    username: postgres
    password: postgres

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate : TRACE